# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/walls/pinkfloyed.jpg'

# Special
background='#0a0a0a'
foreground='#e3e3e4'
cursor='#e3e3e4'

# Colors
color0='#0a0a0a'
color1='#F09828'
color2='#FBFA03'
color3='#8A4996'
color4='#1CBFE5'
color5='#9E9FA0'
color6='#CAC4B1'
color7='#e3e3e4'
color8='#9e9e9f'
color9='#F09828'
color10='#FBFA03'
color11='#8A4996'
color12='#1CBFE5'
color13='#9E9FA0'
color14='#CAC4B1'
color15='#e3e3e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
