--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/walls/pinkfloyed.jpg"

-- Special
background="#0a0a0a"
foreground="#e3e3e4"
cursor="#e3e3e4"

-- Colors
color0="#0a0a0a"
color1="#F09828"
color2="#FBFA03"
color3="#8A4996"
color4="#1CBFE5"
color5="#9E9FA0"
color6="#CAC4B1"
color7="#e3e3e4"
color8="#9e9e9f"
color9="#F09828"
color10="#FBFA03"
color11="#8A4996"
color12="#1CBFE5"
color13="#9E9FA0"
color14="#CAC4B1"
color15="#e3e3e4"
